<a href="https://colab.research.google.com/github/MohamedShoaib3/Algorithms_python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice Notebook

This notebook contains a series of practice problems to help you understand and apply core concepts in NumPy.

---

## 🧩 1. Array Creation
**Question:** Create the following arrays using NumPy:
1. A 1D array with numbers from 0 to 9
2. A 2D array of shape (3, 3) filled with zeros
3. A 2D array of shape (2, 4) filled with ones
4. A 3x3 identity matrix


---


In [22]:
import numpy as np
arr1 = np.arange(10)
print("1D array 0-9:\n", arr1)

1D array 0-9:
 [0 1 2 3 4 5 6 7 8 9]


In [23]:
arr2 = np.zeros((3, 3))
print("\n3x3 array of zeros:\n", arr2)


3x3 array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
arr3 = np.ones((2, 4))
print("\n2x4 array of ones:\n", arr3)


2x4 array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
arr4 = np.eye(3)
print("\n3x3 identity matrix:\n", arr4)


3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



## 🧪 2. Array Inspection
**Question:** Given a NumPy array `arr`, print:
1. Its shape
2. Its data type
3. The number of dimensions
4. The total number of elements

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```

---


In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)
print("Data type:", arr.dtype)
print("Number of dimensions:", arr.ndim)
print("Total number of elements:", arr.size)

Shape: (2, 3)
Data type: int64
Number of dimensions: 2
Total number of elements: 6



## 🔍 3. Indexing and Slicing
**Question:** Using the array below, do the following:
1. Slice the first two rows
2. Get the last column
3. Extract the element in the second row and third column
4. Reverse the rows

```python
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

```


In [27]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
first_two_rows = arr[:2]
print("First two rows:\n", first_two_rows)

last_column = arr[:, -1]
print("\nLast column:\n", last_column)

element_2_3 = arr[1, 2]
print("\nElement at 2nd row, 3rd column:", element_2_3)

reversed_rows = arr[::-1]
print("\nRows reversed:\n", reversed_rows)

First two rows:
 [[10 20 30]
 [40 50 60]]

Last column:
 [30 60 90]

Element at 2nd row, 3rd column: 60

Rows reversed:
 [[70 80 90]
 [40 50 60]
 [10 20 30]]



---

## 🔁 4. More Slicing Practice
**Question:**
Given the array below, extract:
1. All even numbers
2. The second and third rows
3. The last two columns
4. A subarray containing the middle 2x2 block

```python
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

```


In [28]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

even_numbers = arr[arr % 2 == 0]
print("Even numbers:\n", even_numbers)

second_third_rows = arr[1:3]
print("\nSecond and third rows:\n", second_third_rows)

last_two_columns = arr[:, -2:]
print("\nLast two columns:\n", last_two_columns)

middle_block = arr[1:3, 1:3]
print("\nMiddle 2x2 block:\n", middle_block)

Even numbers:
 [ 2  4  6  8 10 12 14 16]

Second and third rows:
 [[ 5  6  7  8]
 [ 9 10 11 12]]

Last two columns:
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]

Middle 2x2 block:
 [[ 6  7]
 [10 11]]



---

## ➕ 5. Arithmetic Operations
**Question:** Perform the following using NumPy arrays:
1. Add two arrays element-wise
2. Multiply two arrays element-wise
3. Raise all elements of an array to the power of 2

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

```

---


In [29]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

sum_array = arr1 + arr2
print("Element-wise sum:", sum_array)

product_array = arr1 * arr2
print("Element-wise product:", product_array)

squared_array = arr1 ** 2
print("arr1 squared:", squared_array)

Element-wise sum: [5 7 9]
Element-wise product: [ 4 10 18]
arr1 squared: [1 4 9]



## 📏 6. Broadcasting
**Question:** Use broadcasting to:
1. Add a 1D array to each row of a 2D array
2. Multiply each row of a 2D array by a 1D array
3. Subtract a scalar from each element in an array
4. Add a column vector to each column of a matrix

```python
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
C = np.array([[1], [2]])

```


In [30]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
C = np.array([[1], [2]])

add_row = A + B
print("Add B to each row of A:\n", add_row)

multiply_row = A * B
print("\nMultiply each row of A by B:\n", multiply_row)

subtract_scalar = A - 5
print("\nSubtract scalar 5 from each element:\n", subtract_scalar)

add_column_vector = A + C
print("\nAdd column vector C to each column of A:\n", add_column_vector)

Add B to each row of A:
 [[11 22 33]
 [14 25 36]]

Multiply each row of A by B:
 [[ 10  40  90]
 [ 40 100 180]]

Subtract scalar 5 from each element:
 [[-4 -3 -2]
 [-1  0  1]]

Add column vector C to each column of A:
 [[2 3 4]
 [6 7 8]]



---

## 🔁 7. More Broadcasting Practice
**Question:** Try these:
1. Add a 1D array of shape (4,) to a 2D array of shape (3,4)
2. Multiply a (3,1) column array to a (1,4) row array and observe the shape
3. Add a scalar to the entire array

```python
A = np.arange(12).reshape(3, 4)
B = np.array([100, 200, 300, 400])
C = np.array([[2], [3], [4]])

```


In [31]:
import numpy as np

A = np.arange(12).reshape(3, 4)
B = np.array([100, 200, 300, 400])
C = np.array([[2], [3], [4]])

add_row = A + B
print("Add 1D array B to each row of A:\n", add_row)
print("-----------------------------")

multiply_col_row = C * B  # Broadcasting يؤدي لمصفوفة (3,4)
print("Multiply column vector C with row vector B:\n", multiply_col_row)
print("Shape:", multiply_col_row.shape)
print("-------------------------------")

add_scalar = A + 10
print("Add scalar 10 to all elements of A:\n", add_scalar)


Add 1D array B to each row of A:
 [[100 201 302 403]
 [104 205 306 407]
 [108 209 310 411]]
-----------------------------
Multiply column vector C with row vector B:
 [[ 200  400  600  800]
 [ 300  600  900 1200]
 [ 400  800 1200 1600]]
Shape: (3, 4)
-------------------------------
Add scalar 10 to all elements of A:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]



---

## 🔃 8. Reshaping and Flattening
**Question:**
1. Reshape a 1D array of 12 elements into a 3x4 matrix
2. Flatten a 2D array into a 1D array

```python
arr = np.arange(12)

```


In [32]:
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
print("Reshaped 1D array into 3x4 matrix:\n", reshaped)
print("--------------------------------------")

flattened = reshaped.flatten()
print("Flattened 2D array into 1D array:\n", flattened)


Reshaped 1D array into 3x4 matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------------------------
Flattened 2D array into 1D array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]



---

## 🔗 9. Stacking and Splitting
**Question:** Stack and split arrays:
1. Stack two (2, 2) arrays vertically and horizontally
2. reshape a (4, 4) array into array of shape (2, 8)


---


In [33]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

v_stack = np.vstack((arr1, arr2))
print("Vertical Stack:\n", v_stack)
print("---------------------------------")

h_stack = np.hstack((arr1, arr2))
print("Horizontal Stack:\n", h_stack)
print("----------------------------------")

arr3 = np.arange(16).reshape(4, 4)
reshaped = arr3.reshape(2, 8)
print("Reshaped (4,4) to (2,8):\n", reshaped)

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
---------------------------------
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
----------------------------------
Reshaped (4,4) to (2,8):
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]



## 🧠 10. Boolean Masking
**Question:**
Given an array:
1. Select all elements > 10
2. Replace all even numbers with -1

```python
arr = np.array([[5, 10, 15], [20, 25, 30]])

```


In [34]:
arr = np.array([[5, 10, 15], [20, 25, 30]])

greater_than_10 = arr[arr > 10]
print("Elements > 10:\n", greater_than_10)
print("--------------------------------------")

arr_even_replaced = arr.copy()
arr_even_replaced[arr_even_replaced % 2 == 0] = -1
print("Array with even numbers replaced by -1:\n", arr_even_replaced)


Elements > 10:
 [15 20 25 30]
--------------------------------------
Array with even numbers replaced by -1:
 [[ 5 -1 15]
 [-1 25 -1]]



---

## 🧮 11. Aggregation
**Question:** Calculate:
1. Sum of all elements
2. Mean of each column
3. Max value in each row
4. Standard deviation of the array

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```


In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
total_sum = np.sum(arr)
print("Sum of all elements:", total_sum)
print("------------------------------------")

mean_per_column = np.mean(arr, axis=0)
print("Mean of each column:", mean_per_column)
print("-----------------------------------")

max_per_row = np.max(arr, axis=1)
print("Max value in each row:", max_per_row)
print("------------------------------------")

std_dev = np.std(arr)
print("Standard deviation of the array:", std_dev)

Sum of all elements: 21
------------------------------------
Mean of each column: [2.5 3.5 4.5]
-----------------------------------
Max value in each row: [3 6]
------------------------------------
Standard deviation of the array: 1.707825127659933



---

## 🧲 12. Dot Product and Matrix Multiplication
**Question:**
1. Multiply two matrices using `np.dot`

```python
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

```


In [36]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
dot_product = np.dot(A, B)
print("Dot Product (Matrix Multiplication):\n", dot_product)

Dot Product (Matrix Multiplication):
 [[19 22]
 [43 50]]



---

## 🔢 13. Random Numbers
**Question:**
1. Generate a 2x3 array of random numbers between 0 and 1
2. Generate 10 random integers between 50 and 100



In [37]:
random_floats = np.random.rand(2, 3)
print("2x3 Random numbers between 0 and 1:\n", random_floats)
print("----------------------------------")

random_ints = np.random.randint(50, 101, size=10)
print("10 Random integers between 50 and 100:\n", random_ints)

2x3 Random numbers between 0 and 1:
 [[0.94512709 0.95716757 0.5185845 ]
 [0.72806593 0.97844883 0.9991891 ]]
----------------------------------
10 Random integers between 50 and 100:
 [95 61 51 71 57 52 80 83 83 66]



---

## 📐 14. Linear Algebra
**Question:**
1. Find the rank of a matrix
2. Compute the inverse of a matrix
3. Compute the determinant of a matrix



---


In [38]:
matrix = np.array([[1, 2],
                   [3, 4]])

rank = np.linalg.matrix_rank(matrix)
print("Rank of the matrix:", rank)
print("-----------------------------")

inverse_matrix = np.linalg.inv(matrix)
print("Inverse of the matrix:\n", inverse_matrix)
print("----------------------------")

determinant = np.linalg.det(matrix)
print("Determinant of the matrix:", determinant)

Rank of the matrix: 2
-----------------------------
Inverse of the matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
----------------------------
Determinant of the matrix: -2.0000000000000004



## ⭐ Bonus Challenge
**Question:**
Given a 2D array of shape (6, 6), extract all 3x3 submatrices (using slicing) and store them in a list.



In [39]:
arr = np.arange(1, 37).reshape(6, 6)
print("Original 6x6 Array:\n", arr)
print("--------------------")

submatrices = []
for i in range(arr.shape[0] - 2):
    for j in range(arr.shape[1] - 2):
        sub = arr[i:i+3, j:j+3]
        submatrices.append(sub)

for idx, mat in enumerate(submatrices, start=1):
    print(f"Submatrix {idx}:\n{mat}")

Original 6x6 Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
--------------------
Submatrix 1:
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
Submatrix 2:
[[ 2  3  4]
 [ 8  9 10]
 [14 15 16]]
Submatrix 3:
[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]]
Submatrix 4:
[[ 4  5  6]
 [10 11 12]
 [16 17 18]]
Submatrix 5:
[[ 7  8  9]
 [13 14 15]
 [19 20 21]]
Submatrix 6:
[[ 8  9 10]
 [14 15 16]
 [20 21 22]]
Submatrix 7:
[[ 9 10 11]
 [15 16 17]
 [21 22 23]]
Submatrix 8:
[[10 11 12]
 [16 17 18]
 [22 23 24]]
Submatrix 9:
[[13 14 15]
 [19 20 21]
 [25 26 27]]
Submatrix 10:
[[14 15 16]
 [20 21 22]
 [26 27 28]]
Submatrix 11:
[[15 16 17]
 [21 22 23]
 [27 28 29]]
Submatrix 12:
[[16 17 18]
 [22 23 24]
 [28 29 30]]
Submatrix 13:
[[19 20 21]
 [25 26 27]
 [31 32 33]]
Submatrix 14:
[[20 21 22]
 [26 27 28]
 [32 33 34]]
Submatrix 15:
[[21 22 23]
 [27 28 29]
 [33 34 35]]
Submatrix 16:
[[22 23 24]
 [28 29 30]
 [34 35 36]]



---

Happy coding! 🎯
